default:
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq rsync
    - apt-get install -y -qq python3.8 python3.8-dev python3.8-venv python3-setuptools libpq-dev
    - export ENV_DIR=$SERVER_TEST_DIR/$CI_COMMIT_REF_NAME
    - export DATABASE_URL=$DATABASE_URL
    - export TEST_DATABASE_URL=$TEST_DATABASE_URL
    - export PRODUCTION_DATABASE_URL=$PRODUCTION_DATABASE_URL


stages:
  - unittest
  - dev-deploy
  - prod-deploy


test:
  stage: unittest
  script:
    - export FLASK_CONFIG=config.TestingConfig
    - mkdir -p $ENV_DIR/current
    - rsync -a --info=progress2 --delete . $ENV_DIR/current/
    - rm -rf $ENV_DIR/venv
    - python3.8 -m venv $ENV_DIR/venv
    - source $ENV_DIR/venv/bin/activate && pip install -r $ENV_DIR/current/requirements.txt && flask db migrate && flask db upgrade
  tags:
    - sys-ya
  when: manual


dev-deploy:
  stage: dev-deploy
  timeout: 20m
  script:
    - sudo systemctl stop sys360.service
    - rsync -a --info=progress2 --delete . $LOCAL_DIR/app
    - rm -rf $LOCAL_DIR/venv
    - export FLASK_CONFIG=config.DevelopmentConfig
    - python3.8 -m venv $LOCAL_DIR/venv && source $LOCAL_DIR/venv/bin/activate && pip install -r $LOCAL_DIR/app/requirements.txt && export FLASK_APP=$LOCAL_DIR/app/main.py
    - source $LOCAL_DIR/venv/bin/activate && flask db migrate
    - source $LOCAL_DIR/venv/bin/activate && flask db upgrade
    - sudo systemctl start sys360.service
  tags:
    - sys-ya
  only:
    - master

prod-deploy:
  stage: prod-deploy
  timeout: 20m
  script:
    - echo prod
  tags:
    - sys-ya
  when: manual
  only:
    - master