"""empty message

Revision ID: 397893a66263
Revises: 89b7cdf8d131
Create Date: 2020-02-27 23:33:23.501950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '397893a66263'
down_revision = '89b7cdf8d131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkouts', sa.Column('end', sa.DateTime(), nullable=False, comment='время конца задачи'))
    op.drop_column('checkouts', 'stop')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkouts', sa.Column('stop', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='время конца задачи'))
    op.drop_column('checkouts', 'end')
    # ### end Alembic commands ###
