"""empty message

Revision ID: 5078e1698521
Revises: 397893a66263
Create Date: 2020-03-23 03:30:07.163814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5078e1698521'
down_revision = '397893a66263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'franchises', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'franchises', type_='unique')
    # ### end Alembic commands ###
