"""empty message

Revision ID: 89b7cdf8d131
Revises: ccb90db6c73c
Create Date: 2020-02-27 23:01:59.803163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b7cdf8d131'
down_revision = 'ccb90db6c73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False, comment='время начала задачи'),
    sa.Column('stop', sa.DateTime(), nullable=False, comment='время конца задачи'),
    sa.Column('worker', sa.Integer(), nullable=False, comment='пользователь с ролью работник'),
    sa.Column('type', sa.Enum('regular', 'extraordinary', name='typecheckout'), nullable=False, comment='Тип проверки'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['worker'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('checkout', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False, comment='статус задачи'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='название задачи'),
    sa.ForeignKeyConstraint(['checkout'], ['checkouts.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False, comment='название подзадачи'),
    sa.ForeignKeyConstraint(['task'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_tasks')
    op.drop_table('tasks')
    op.drop_table('checkouts')
    # ### end Alembic commands ###
