"""empty message

Revision ID: 8d53191574cc
Revises: b2be45a64e42
Create Date: 2020-02-25 17:50:37.793096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d53191574cc'
down_revision = 'b2be45a64e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('franchises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('objects', 'shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('objects', 'title',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('objects', 'type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('objects', 'x',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('objects', 'y',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shops', 'address',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.add_column('users', sa.Column('franchise_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.create_foreign_key(None, 'users', 'franchises', ['franchise_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_column('users', 'franchise_id')
    op.alter_column('shops', 'address',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('objects', 'y',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('objects', 'x',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('objects', 'type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('objects', 'title',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('objects', 'shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('franchises')
    # ### end Alembic commands ###
