"""empty message

Revision ID: bf56a505cc0a
Revises: abd93b35a846
Create Date: 2020-03-25 13:31:45.258741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf56a505cc0a'
down_revision = 'abd93b35a846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roles_name', table_name='roles')
    op.create_unique_constraint(None, 'roles', ['name'])
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_index('ix_roles_name', 'roles', ['name'], unique=True)
    # ### end Alembic commands ###
